server:
  port: 9002
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:rishabh

  application:
    name: DEPARTMENT-SERVICE
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost